# Studing the pandemic
### What numbers have to say about Covid-19 in Europe?

This notebook is focused on exploring and cleaning the data for the analysis on Covid-19. The main goal of the analysis is to find out what is the relationship between positive cases and deaths in the different phases of the pandemic. The continent we focus is Europe. We are also going to compare Greece, my country, with other European countries.

You can get a copy of the dataset by following the [link](https://ourworldindata.org/coronavirus-testing). As we'll see below the dataset has many useful information about the new cases, deaths tests and even demographics. With so much information we can come up with many conclusions about the effects of the pandeminc gloabally.

The basic steps for cleaning the dataset are
* Decide which columns we'll need for our analysis.
* Check if we have null values in our data.
* Decide what to do with null values.
* Check if we have values that don't make sense( such as negative values for cases and deaths)
* Correct those values.

You can follow the analysis [here]().

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir('../../Data/01_Original_data')

## Data overview

After loading the data we have a very basic overview of the values we have available. AS we can see there are many null values. This is probably because at the early stages of the pandemic most countries collected no data. Another reason we might have null values is because countries did not report their data for a specific day.

In [3]:
df = pd.read_csv('data.csv')
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

## Data for Europe

As we said before we'll focus on Europe. So the first logical step is to isolate that data. Again we see the same patern for the null values but it is something that we expected in the first place.

In [4]:
df = df.loc[df['continent'] == 'Europe']
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
1441,ALB,Europe,Albania,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,7.1,51.2,NaN,2.89,78.57,0.795,NaN,NaN,NaN,NaN
1442,ALB,Europe,Albania,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,7.1,51.2,NaN,2.89,78.57,0.795,NaN,NaN,NaN,NaN
1443,ALB,Europe,Albania,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,7.1,51.2,NaN,2.89,78.57,0.795,NaN,NaN,NaN,NaN
1444,ALB,Europe,Albania,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,7.1,51.2,NaN,2.89,78.57,0.795,NaN,NaN,NaN,NaN
1445,ALB,Europe,Albania,2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,...,7.1,51.2,NaN,2.89,78.57,0.795,-190.8,-4.34,2.88,-66.412942

## More information

Now that we have our data we dive deeper to find more information about it. First we get an idea about the different columns we have in the dataset and the total number of rows, columns and non-null values for each column. The data type is also important to look after. For example we want to treat the date column as an actual date when we are searching for different values. The second thing we do is to get a rough idea about the numeric values of the dataset. Specifically we'll take a close look at the minimum values for the columns we care. Most of them can't be negative values because they represent data which is at least zero.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35760 entries, 1441 to 155517
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    35760 non-null  object
 1   continent                                   35760 non-null  object
 2   location                                    35760 non-null  object
 3   date                                        35760 non-null  object
 4   total_cases                                 34939 non-null  float64
 5   new_cases                                   34930 non-null  float64
 6   new_cases_smoothed                          34685 non-null  float64
 7   total_deaths                                32749 non-null  float64
 8   new_deaths                                  32733 non-null  float64
 9   new_deaths_smoothed                         32723 non-null  float64
 10  total_cases_per_million                     34939 non-null  float64
 11  new_cases_per_million                       34930 non-null  float64
 12  new_cases_smoothed_per_million              34685 non-null  float64
 13  total_deaths_per_million                    32749 non-null  float64
 14  new_deaths_per_million                      32733 non-null  float64
 15  new_deaths_smoothed_per_million             32723 non-null  float64
 16  reproduction_rate                           30839 non-null  float64
 17  icu_patients                                15890 non-null  float64
 18  icu_patients_per_million                    15890 non-null  float64
 19  hosp_patients                               18910 non-null  float64
 20  hosp_patients_per_million                   18910 non-null  float64
 21  weekly_icu_admissions                       3780 non-null   float64
 22  weekly_icu_admissions_per_million           3780 non-null   float64
 23  weekly_hosp_admissions                      7629 non-null   float64
 24  weekly_hosp_admissions_per_million          7629 non-null   float64
 25  new_tests                                   23601 non-null  float64
 26  total_tests                                 24184 non-null  float64
 27  total_tests_per_thousand                    24184 non-null  float64
 28  new_tests_per_thousand                      23601 non-null  float64
 29  new_tests_smoothed                          27425 non-null  float64
 30  new_tests_smoothed_per_thousand             27425 non-null  float64
 31  positive_rate                               25776 non-null  float64
 32  tests_per_case                              25697 non-null  float64
 33  tests_units                                 27736 non-null  object
 34  total_vaccinations                          13426 non-null  float64
 35  people_vaccinated                           12851 non-null  float64
 36  people_fully_vaccinated                     12499 non-null  float64
 37  total_boosters                              5852 non-null   float64
 38  new_vaccinations                            11819 non-null  float64
 39  new_vaccinations_smoothed                   19514 non-null  float64
 40  total_vaccinations_per_hundred              13426 non-null  float64
 41  people_vaccinated_per_hundred               12851 non-null  float64
 42  people_fully_vaccinated_per_hundred         12499 non-null  float64
 43  total_boosters_per_hundred                  5852 non-null   float64
 44  new_vaccinations_smoothed_per_million       19514 non-null  float64
 45  new_people_vaccinated_smoothed              19267 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  19267 non-null  float64
 47  stringency_index                            31348 non-null  float64
 48  population                                  35760 non-null  float64
 49  population_density                          34358 non-null  float64
 50  median_age                                  28726 non-null  float64
 51  aged_65_older                               28726 non-null  float64
 52  aged_70_older                               28013 non-null  float64
 53  gdp_per_capita                              30132 non-null  float64
 54  extreme_poverty                             21488 non-null  float64
 55  cardiovasc_death_rate                       29434 non-null  float64
 56  diabetes_prevalence                         31560 non-null  float64
 57  female_smokers                              28721 non-null  float64
 58  male_smokers                                28721 non-null  float64
 59  handwashing_facilities                      2120 non-null   float64
 60  hospital_beds_per_thousand                  30852 non-null  float64
 61  life_expectancy                             34366 non-null  float64
 62  human_development_index                     30140 non-null  float64
 63  excess_mortality_cumulative_absolute        3341 non-null   float64
 64  excess_mortality_cumulative                 3341 non-null   float64
 65  excess_mortality                            3353 non-null   float64
 66  excess_mortality_cumulative_per_million     3341 non-null   float64
dtypes: float64(62), object(5)
memory usage: 18.6+ MB

In [6]:
pd.set_option("display.max_columns", None)
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,3.493900e+04,34930.000000,34685.000000,32749.000000,32733.000000,32723.000000,34939.000000,34930.000000,34685.000000,32749.000000,32733.000000,32723.000000,30839.000000,15890.000000,15890.000000,18910.000000,18910.000000,3780.000000,3780.000000,7629.000000,7629.000000,2.360100e+04,2.418400e+04,24184.000000,23601.000000,2.742500e+04,27425.000000,25776.000000,25697.000000,1.342600e+04,1.285100e+04,1.249900e+04,5.852000e+03,1.181900e+04,1.951400e+04,13426.000000,12851.000000,12499.000000,5852.000000,19514.000000,19267.000000,19267.000000,31348.000000,3.576000e+04,34358.000000,28726.000000,28726.000000,28013.000000,30132.000000,21488.000000,29434.000000,31560.000000,28721.000000,28721.000000,2120.000000,30852.000000,34366.000000,30140.000000,3.341000e+03,3341.000000,3353.000000,3341.000000
mean,7.034110e+05,3933.891039,3851.493061,15842.790192,50.163352,49.898321,55178.980144,324.751177,316.984719,974.288876,3.143152,3.122733,1.082293,525.690686,24.594499,2896.381227,176.845376,536.187566,15.160393,3205.437148,93.182293,7.338080e+04,1.635191e+07,1273.731149,5.704536,7.217672e+04,5.336566,0.086225,73.285356,1.455671e+07,7.892034e+06,6.720150e+06,2.213209e+06,8.817656e+04,6.188421e+04,80.054261,42.048997,36.113526,11.669002,4218.268166,26051.474957,0.172809,52.721389,1.532945e+07,622.185431,42.086420,17.745908,11.794488,33463.282375,0.901936,229.110338,6.545187,23.392566,35.516006,93.978078,5.157423,79.796960,0.880373,1.885912e+04,5.958447,12.914730,942.886422
std,1.643352e+06,16222.607562,14713.123439,33933.558678,137.000130,128.502726,61185.016743,912.199941,714.410279,942.597591,6.438251,4.969534,0.338817,966.388792,25.405044,5904.675095,220.718252,691.271903,15.923112,5715.232723,107.525784,1.831939e+05,4.164156e+07,2376.513991,12.169468,1.671653e+05,10.778061,0.097844,201.520254,2.964998e+07,1.494079e+07,1.320829e+07,6.342513e+06,1.788483e+05,1.327876e+05,62.570307,28.475745,28.263900,17.173414,3760.597022,64061.868644,0.206117,17.600675,2.767586e+07,2768.710126,2.575191,2.784546,2.228457,17749.349583,1.275696,124.723546,1.986277,7.550645,10.543798,4.930993,2.374830,3.511841,0.056446,5.227539e+04,8.629089,22.807429,1314.006510
min,1.000000e+00,-74937.000000,-6223.000000,1.000000,-1918.000000,-232.143000,0.012000,-2123.457000,-272.971000,0.007000,-75.911000,-10.844000,-0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.100000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.120000e+02,3.404000,37.300000,10.864000,6.955000,5189.972000,0.100000,86.060000,3.280000,5.900000,15.200000,86.979000,2.220000,71.900000,0.750000,-1.777920e+04,-28.450000,-68.420000,-1826.595723
25%,5.105500e+03,17.000000,34.143000,139.000000,0.000000,0.571000,4753.054500,10.661000,19.460000,122.317000,0.000000,0.201000,0.880000,27.000000,5.227000,110.000000,26.783000,48.000000,3.608500,226.000000,18.630000,3.519000e+03,5.147425e+05,132.580000,1.020000,3.662000e+03,1.100000,0.017200,8.200000,4.233855e+05,2.856220e+05,2.026550e+05,1.490000e+02,3.408500e+03,1.747000e+03,21.120000,13.530000,7.700000,0.000000,1570.000000,569.000000,0.043000,40.740000,6.348140e+05,65.180000,40.300000,15.070000,9.788000,22669.797000,0.200000,122.137000,4.910000,19.600000,27.300000,86.979000,3.320000,76.880000,0.829000,-5.050000e+01,-0.450000,-0.610000,-36.388611
50%,9.491600e+04,313.000000,392.429000,2130.000000,5.000000,5.714000,36364.851000,81.585000,105.461000,749.327000,0.757000,1.147000,1.060000,130.000000,15.264000,543.000000,86.829000,261.000000,11.336000,1078.000000,57.140000,1.388600e+04,2.627744e+06,519.339500,2.368000,1.522300e+04,2.364000,0.049000,20.300000,2.206146e+06,1.328404e+06,1.155920e+06,5.306950e+04,1.672800e+04,1.136600e+04,74.565000,44.560000,33.370000,1.740000,3129.500000,4061.000000,0.099000,51.850000,5.449270e+06,106.749000,42.400000,18.577000,11.976000,31400.840000,0.500000,168.711000,5.810000,23.000000,34.800000,97.164000,4.510000,81.320000,0.892000,2.616500e+03,5.460000,6.590000,538.898930
75%,5.597800e+05,1887.750000,2055.000000,12768.000000,29.000000,31.286000,84390.726500,296.443000,315.258000,1547.456000,3.817000,4.200000,1.260000,514.000000,36.973500,2422.500000,249.599000,764.750000,21.069000,4518.000000,128.313000,4.780800e+04,1.111541e+07,1301.123500,4.931000,4.847800e+04,4.519000,0.121425,57.100000,1.116434e+07,5.933710e+06,5.601000e+06,1.130686e+06,7.692450e+04,4.857725e+04,127.427500,67.015000,61.580000,19.280000,6104.000000,19088.500000,0.227000,65.740000,1.037075e+07,205.859000,43.900000,19.718000,13.433000,45229.245000,1.000000,329.635000,7.770000,28.200000,44.400000,97.719000,6.620000,82.400000,0.931000,1.678360e+04,11.620000,19.350000,1597.773044
max,2.085632e+07,502507.000000,366554.714000,329264.000000,1820.000000,1248.857000,496605.712000,37712.212000,16032.222000,4922.096000,267.134000,144.167000,3.770000,7019.000000,176.791000,39255.000000,1544.082000,4838.000000,221.212000,111902.000000,766.914000,2.945871e+06,4.459817e+08,26077.664000,325.760000,1.866999e+06,147.603000,0.951500,5439.800000,1.666335e+08,7.719742e+07,7.034182e+07,4.516992e+07,2.389472e+06,1.129105e+06,331.070000,122.860000,120.950000,87.260000,70706.000000,593907.000000,3.087000,100.000000,1.459120e+08,19347.500000,47.900000,23.021000,16.240000,94277.965000,5.700000,539.849000,10.080000,44.000000,58.300000,97.719000,13.800000,86.750000,0.957000,1.080748e+06,46.810000,157.230000,8626.892312

In [7]:
number_of_countries = len(pd.unique(df['location']))
print(f'Number of unique countries in dataset: {number_of_countries}')

Number of unique countries in dataset: 51

## Let's talk about date first.

It is important to understand the time period that our dataset covers. If we know that we can relate our data with some events that happend worldwide. For example we can see the effects of the lockdown in Europe. Our data begins from the 6th of January 2020 and it ends at the 7th of February 2022. So we have data that covers all phases of the pandemic.

In [8]:
df['date'] = pd.to_datetime(df['date'])

In [9]:
df.sort_values(by='date')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
45400,EST,Europe,Estonia,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1325188.0,31.033,42.7,19.452,13.491,29481.252,0.5,255.569,4.02,24.5,39.3,NaN,4.690,78.74,0.892,NaN,NaN,NaN,NaN
80558,LVA,Europe,Latvia,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1866934.0,31.212,43.9,19.754,14.136,25063.846,0.7,350.060,4.91,25.6,51.0,NaN,5.570,75.29,0.866,NaN,NaN,NaN,NaN
57575,GRC,Europe,Greece,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,10370747.0,83.479,45.3,20.396,14.524,24574.382,1.5,175.695,4.55,35.3,52.0,NaN,4.210,82.24,0.888,NaN,NaN,NaN,NaN
45401,EST,Europe,Estonia,2020-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1325188.0,31.033,42.7,19.452,13.491,29481.252,0.5,255.569,4.02,24.5,39.3,NaN,4.690,78.74,0.892,NaN,NaN,NaN,NaN
80559,LVA,Europe,Latvia,2020-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1866934.0,31.212,43.9,19.754,14.136,25063.846,0.7,350.060,4.91,25.6,51.0,NaN,5.570,75.29,0.866,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87618,LUX,Europe,Luxembourg,2022-02-07,168988.0,3030.0,1571.857,964.0,6.0,1.714,266200.808,4773.052,2476.091,1518.555,9.452,2.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.56,634814.0,231.447,39.7,14.312,9.842,94277.965,0.2,128.275,4.42,20.9,26.0,NaN,4.510,82.25,0.916,NaN,NaN,NaN,NaN
92575,MLT,Europe,Malta,2022-02-07,69175.0,175.0,208.286,570.0,1.0,2.857,134034.102,339.082,403.576,1104.437,1.938,5.536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1859.0,1702683.0,3299.134,3.602,2307.0,4.47,NaN,NaN,tests performed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.78,516100.0,1454.037,42.4,19.426,11.324,36513.323,0.2,168.711,8.83,20.9,30.2,NaN,4.485,82.53,0.895,NaN,NaN,NaN,NaN
96285,MDA,Europe,Moldova,2022-02-07,468782.0,1511.0,4012.000,10776.0,8.0,19.143,116495.797,375.495,997.012,2677.916,1.988,4.757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963941.0,NaN,1016526.0,NaN,NaN,4604.0,48.81,NaN,25.26,NaN,1144.0,NaN,NaN,47.22,4024025.0,123.655,37.6,10.864,6.955,5189.972,0.2,408.502,5.72,5.9,44.6,86.979,5.800,71.90,0.750,NaN,NaN,NaN,NaN
98388,MNE,Europe,Montenegro,2022-02-07,223774.0,312.0,571.286,2610.0,9.0,6.571,356299.090,496.775,909.617,4155.713,14.330,10.463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,657035.0,287476.0,278519.0,91040.0,87.0,434.0,104.61,45.77,44.35,14.5,691.0,72.0,0.011,NaN,628051.0,46.280,39.1,14.762,9.395,16409.288,1.0,387.305,10.08,44.0,47.9,NaN,3.861,76.88,0.829,NaN,NaN,NaN,NaN
155517,VAT,Europe,Vatican,2022-02-07,29.0,0.0,0.000,NaN,NaN,NaN,35714.286,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN,NaN,NaN,NaN,NaN

## Handle null and wrong values.

The next step is to find how many missing and wrong values we have. In this case we'll convert missing values into 0. For the wrong values(for example negative new cases or deaths) we have to think more before making any decisions. I tried to find the correct values from other sources, but we don't have any reported. With this in mind I changed all wrong values to 0.

In [10]:
print(f"Number of missing values for new cases: {df['new_cases'].isnull().sum()}")

df['new_cases'] = df['new_cases'].fillna(0)

Number of missing values for new cases: 830

In [11]:
print(f"Total new cases with negative value: {len(df.loc[df['new_cases'] < 0])}")

df.loc[df['new_cases'] < 0, 'new_cases'] = 0

Total new cases with negative value: 32

In [12]:
print(f"Number of missing values for new deaths: {df['new_deaths'].isnull().sum()}")

df['new_deaths'] = df['new_deaths'].fillna(0)

Number of missing values for new deaths: 3027

In [13]:
print(f"Total new deaths with negative value: {len(df.loc[df['new_deaths'] < 0])}")

df.loc[df['new_deaths'] < 0, 'new_deaths'] = 0

Total new deaths with negative value: 78

In [14]:
print(f"Number of missing values for new cases per million: {df['new_cases_per_million'].isnull().sum()}")

df['new_cases_per_million'] = df['new_cases_per_million'].fillna(0)

Number of missing values for new cases per million: 830

In [15]:
print(f"Total new cases per million with negative value: {len(df.loc[df['new_cases_per_million'] < 0])}")

df.loc[df['new_cases_per_million'] < 0, 'new_cases_per_million'] = 0

Total new cases per million with negative value: 32

In [16]:
print(f"Number of missing values for new deaths per million: {df['new_deaths_per_million'].isnull().sum()}")

df['new_deaths_per_million'] = df['new_deaths_per_million'].fillna(0)

Number of missing values for new deaths per million: 3027

In [17]:
print(f"Total new deathsper million with negative value: {len(df.loc[df['new_deaths_per_million'] < 0])}")

df.loc[df['new_deaths_per_million'] < 0, 'new_deaths_per_million'] = 0

Total new deathsper million with negative value: 78

In [18]:
print(f"Number of rows with missing reproduction rate: {df['reproduction_rate'].isnull().sum()}")

df['reproduction_rate'] = df['reproduction_rate'].fillna(0)

Number of rows with missing reproduction rate: 4921

In [19]:
print(f"Total reproduction rates with negative value: {len(df.loc[df['reproduction_rate'] < 0])}")

df.loc[df['reproduction_rate'] < 0, 'reproduction_rate'] = 0

Total reproduction rates with negative value: 6

In [20]:
print(f"Number of rows with missing icu patients: {df['icu_patients'].isnull().sum()}")

df['icu_patients'] = df['icu_patients'].fillna(0)

Number of rows with missing icu patients: 19870

In [21]:
print(f"Number of rows with missing icu patients per million: {df['icu_patients_per_million'].isnull().sum()}")

df['icu_patients_per_million'] = df['icu_patients_per_million'].fillna(0)

Number of rows with missing icu patients per million: 19870

In [22]:
print(f"Number of rows with missing hospital patients: {df['hosp_patients'].isnull().sum()}")

df['hosp_patients'] = df['hosp_patients'].fillna(0)

Number of rows with missing hospital patients: 16850

In [23]:
print(f"Number of rows with missing hospital patients per million: {df['hosp_patients_per_million'].isnull().sum()}")

df['hosp_patients_per_million'] = df['hosp_patients_per_million'].fillna(0)

Number of rows with missing hospital patients per million: 16850

In [24]:
print(f"Number of rows with missing weekly icu admissions per million: {df['weekly_icu_admissions_per_million'].isnull().sum()}")

df['weekly_icu_admissions_per_million'] = df['weekly_icu_admissions_per_million'].fillna(0)

Number of rows with missing weekly icu admissions per million: 31980

In [25]:
print(f"Number of rows with missing weekly hospital admissions per million: {df['weekly_hosp_admissions_per_million'].isnull().sum()}")

df['weekly_hosp_admissions_per_million'] = df['weekly_hosp_admissions_per_million'].fillna(0)

Number of rows with missing weekly hospital admissions per million: 28131

In [26]:
print(f"Number of rows with missing new tests: {df['new_tests'].isnull().sum()}")

df['new_tests'] = df['new_tests'].fillna(0)

Number of rows with missing new tests: 12159

In [27]:
print(f"Number of rows with missing new tests per thousand: {df['new_tests_per_thousand'].isnull().sum()}")

df['new_tests_per_thousand'] = df['new_tests_per_thousand'].fillna(0)

Number of rows with missing new tests per thousand: 12159

In [28]:
print(f"Number of rows with missing positive rate: {df['positive_rate'].isnull().sum()}")

df['positive_rate'] = df['positive_rate'].fillna(0)

Number of rows with missing positive rate: 9984

In [29]:
print(f"Number of rows with missing tests per case: {df['tests_per_case'].isnull().sum()}")

df['tests_per_case'] = df['tests_per_case'].fillna(0)

Number of rows with missing tests per case: 10063

## Save the final dataset

In [31]:
#Final dataset.
columns_to_keep = ['iso_code','location', 'date', 'new_cases', 'new_deaths', 'new_cases_per_million', 'new_deaths_per_million', 'reproduction_rate',
                  'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions_per_million',
                  'weekly_hosp_admissions_per_million', 'new_tests', 'new_tests_per_thousand', 'positive_rate', 'tests_per_case']
os.chdir('../02_Cleaned_data')
df[columns_to_keep].to_csv('cleaned_data.csv', index= False)
df[columns_to_keep].head()

,iso_code,location,date,new_cases,new_deaths,new_cases_per_million,new_deaths_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions_per_million,weekly_hosp_admissions_per_million,new_tests,new_tests_per_thousand,positive_rate,tests_per_case
1441,ALB,Albania,2020-02-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.003,0.0,0.0
1442,ALB,Albania,2020-02-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.002,0.0,0.0
1443,ALB,Albania,2020-02-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.001,0.0,0.0
1444,ALB,Albania,2020-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000,0.0,0.0
1445,ALB,Albania,2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.003,0.0,0.0